In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('Filtered_MOG_assays.csv')
df.head()

,IEDB Receptor ID,Reference Name,Epitope Name,Chain 1 V Gene,Chain 1 D Gene,Chain 1 J Gene,Chain 1 CDR3,Chain 2 V Gene,Chain 2 D Gene,Chain 2 J Gene,Chain 2 CDR3,count
0,1805,2D2,MEVGWYRSPFSRVVHLYRNGK,TRAV9D-4,NaN,NaN,VYFCALRSYNFGF,TRBV16*04,NaN,TRBJ2-1,ASSLDCGANP,1
1,19070,NaN,MEVGWYRSPFSRVVHLYRNGK,TRAV9D-4,NaN,NaN,NaN,TCRVB8-2,NaN,TRBJ2-1,GETGGNYAEQ,1
2,26413,T12-1359,MEVGWYRSPFSRVVHLYRNGK,TRAV4D-3*03,NaN,TRAJ31*01,CAAEAGNNRIFF,TRBV13-2,TRBD2,TRBJ2-1,CASGETGGNYAEQFF,1
3,26414,T6-145,MEVGWYRSPFSRVVHLYRNGK,TRAV4D-3*03,NaN,TRAJ17*01,CAAGNSAGNKLTF,TRBV13-2,TRBD2,TRBJ2-1,CASGETGGNYAEQFF,1
4,26415,T6-71,MEVGWYRSPFSRVVHLYRNGK,TRAV7D-2*02,NaN,TRAJ52*01,CAASGANTGKLTF,TRBV13-2,TRBD2,TRBJ2-1,CASGETGGNYAEQFF,1

In [18]:
# df.dropna(inplace=True)
df2 = df[["Chain 1 CDR3", "Chain 2 CDR3", "Epitope Name"]]
df2.dropna(axis=0, inplace=True)
df2['value'] = 1
df2.head()

/scratch/slurm-6128184/ipykernel_650/2234482220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(axis=0, inplace=True)
/scratch/slurm-6128184/ipykernel_650/2234482220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['value'] = 1

    Chain 1 CDR3     Chain 2 CDR3           Epitope Name  value
0  VYFCALRSYNFGF       ASSLDCGANP  MEVGWYRSPFSRVVHLYRNGK      1
2   CAAEAGNNRIFF  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
3  CAAGNSAGNKLTF  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
4  CAASGANTGKLTF  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
5  CAMGGGSNAKLTF  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1

In [17]:
df2.to_csv('ab_train.csv')

In [20]:
df3 = df2[["Chain 2 CDR3", "Epitope Name", "value"]]
df3.head()

      Chain 2 CDR3           Epitope Name  value
0       ASSLDCGANP  MEVGWYRSPFSRVVHLYRNGK      1
2  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
3  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
4  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
5  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1

In [21]:
df3.to_csv('b_train.csv')

In [22]:
df3

       Chain 2 CDR3           Epitope Name  value
0        ASSLDCGANP  MEVGWYRSPFSRVVHLYRNGK      1
2   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
3   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
4   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
5   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
6   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
7   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
8   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
9   CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
10  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
11  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
12  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
13  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
14  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
15  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
16  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
17  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
18  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
19  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
20  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
21  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
22  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
23  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
24  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
25  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
26  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
27  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
28  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
29  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
30  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
31  CASGETGGNYAEQFF  MEVGWYRSPFSRVVHLYRNGK      1
32   CASGDWGGEDTLYF  MEVGWYRSPFSRVVHLYRNGK      1
33  CASSIADSSAETLYF  MEVGWYRSPFSRVVHLYRNGK      1
34   CASGDAGTGYEQYF  MEVGWYRSPFSRVVHLYRNGK      1
35   CASNGLGEEDTQYF  MEVGWYRSPFSRVVHLYRNGK      1
36     CGARDTLYEQYF  MEVGWYRSPFSRVVHLYRNGK      1